binary_sensor:
  - platform: gpio
    id: bs_button_1_raw
    name: TX Button 1 (Raw)
    internal: True
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_1_press
    on_release:
      - script.execute: sc_button_1_release

  - platform: template
    id: bs_button_1
    name: TX Button 1
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_1_raw).state;
    on_press:
      then:
        - logger.log: "TX Button 1 was pressed"
    on_release:
      then:
        - logger.log: "TX Button 1 was released"

  - platform: gpio
    id: bs_button_2_raw
    name: TX Button 2 (Raw)
    internal: True
    pin:
      number: GPIO35
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_2_press
    on_release:
      - script.execute: sc_button_2_release

  - platform: template
    id: bs_button_2
    name: TX Button 2
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_2_raw).state;
    on_press:
      then:
        - logger.log: "TX Button 2 was pressed"
    on_release:
      then:
        - logger.log: "TX Button 2 was released"

  - platform: gpio
    id: bs_button_3_raw
    name: TX Button 3 (Raw)
    internal: True
    pin:
      number: GPIO34
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_3_press
    on_release:
      - script.execute: sc_button_3_release

  - platform: template
    id: bs_button_3
    name: TX Button 3
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_3_raw).state;
    on_press:
      then:
        - logger.log: "TX Button 3 was pressed"
    on_release:
      then:
        - logger.log: "TX Button 3 was released"

  - platform: gpio
    id: bs_button_4_raw
    name: TX Button 4 (Raw)
    internal: True
    pin:
      number: GPIO39
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_4_press
    on_release:
      - script.execute: sc_button_4_release

  - platform: template
    id: bs_button_4
    name: TX Button 4
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_4_raw).state;
    on_press:
      then:
        - logger.log: "TX Button 4 was pressed"
    on_release:
      then:
        - logger.log: "TX Button 4 was released"

  - platform: gpio
    id: bs_button_5_raw
    name: TX Button 5 (Raw)
    internal: True
    pin:
      number: GPIO36
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_5_press
    on_release:
      - script.execute: sc_button_5_release

  - platform: template
    id: bs_button_5
    name: TX Button 5
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_5_raw).state;
    on_press:
      then:
        - logger.log: "TX Button 5 was pressed"
    on_release:
      then:
        - logger.log: "TX Button 5 was released"

  - platform: gpio
    id: bs_button_6_raw
    name: TX Button 6 (Raw)
    internal: True
    pin:
      number: GPIO27
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_6_press
    on_release:
      - script.execute: sc_button_6_release

  - platform: template
    id: bs_button_6
    name: TX Button 6
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_6_raw).state;
    on_press:
      then:
        - logger.log: "TX Button 6 was pressed"
    on_release:
      then:
        - logger.log: "TX Button 6 was released"
