binary_sensor:
  - platform: gpio
    id: bs_button_1_raw
    name: Button 1 (Raw)
    internal: True
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_1_press
    on_release:
      - script.execute: sc_button_1_release

  - platform: template
    id: bs_button_1
    name: Button 1 (Virtual)
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_1_raw).state;
    on_press:
      then:
        - logger.log: "Button 1 (Virtual) was pressed"
    on_release:
      then:
        - logger.log: "Button 1 (Virtual) was released"

  - platform: gpio
    id: bs_button_2_raw
    name: Button 2 (Raw)
    internal: True
    pin:
      number: GPIO35
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_2_press
    on_release:
      - script.execute: sc_button_2_release

  - platform: template
    id: bs_button_2
    name: Button 2 (Virtual)
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_2_raw).state;
    on_press:
      then:
        - logger.log: "Button 2 (Virtual) was pressed"
    on_release:
      then:
        - logger.log: "Button 2 (Virtual) was released"

  - platform: gpio
    id: bs_button_3_raw
    name: Button 3 (Raw)
    internal: True
    pin:
      number: GPIO34
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_3_press
    on_release:
      - script.execute: sc_button_3_release

  - platform: template
    id: bs_button_3
    name: Button 3 (Virtual)
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_3_raw).state;
    on_press:
      then:
        - logger.log: "Button 3 (Virtual) was pressed"
    on_release:
      then:
        - logger.log: "Button 3 (Virtual) was released"

  - platform: gpio
    id: bs_button_4_raw
    name: Button 4 (Raw)
    internal: True
    pin:
      number: GPIO39
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_4_press
    on_release:
      - script.execute: sc_button_4_release

  - platform: template
    id: bs_button_4
    name: Button 4 (Virtual)
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_4_raw).state;
    on_press:
      then:
        - logger.log: "Button 4 (Virtual) was pressed"
    on_release:
      then:
        - logger.log: "Button 4 (Virtual) was released"

  - platform: gpio
    id: bs_button_5_raw
    name: Button 5 (Raw)
    internal: True
    pin:
      number: GPIO36
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_5_press
    on_release:
      - script.execute: sc_button_5_release

  - platform: template
    id: bs_button_5
    name: Button 5 (Virtual)
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_5_raw).state;
    on_press:
      then:
        - logger.log: "Button 5 (Virtual) was pressed"
    on_release:
      then:
        - logger.log: "Button 5 (Virtual) was released"

  - platform: gpio
    id: bs_button_6_raw
    name: Button 6 (Raw)
    internal: True
    pin:
      number: GPIO27
      mode:
        input: true
        pullup: true
      inverted: true
    on_press:
      - script.execute: sc_button_6_press
    on_release:
      - script.execute: sc_button_6_release

  - platform: template
    id: bs_button_6
    name: Button 6 (Virtual)
    internal: False
    icon: mdi:gesture-tap-box
    lambda: |-
      return id(bs_button_6_raw).state;
    on_press:
      then:
        - logger.log: "Button 6 (Virtual) was pressed"
    on_release:
      then:
        - logger.log: "Button 6 (Virtual) was released"
